//postActions
export const GETALL_REQUEST = "POST_GETALL_REQUEST";
export const GETALL_SUCCESS = "POST_GETALL_SUCCESS";
export const GETALL_FAILURE = "POST_GETALL_FAILURE";

export const SHAREPOST_REQUEST = "POST_SHAREPOST_REQUEST";
export const SHAREPOST_SUCCESS = "POST_SHAREPOST_SUCCESS";
export const SHAREPOST_FAILURE = "POST_SHAREPOST_FAILURE";

export const EDITPOST_REQUEST = "POST_EDITPOST_REQUEST";
export const EDITPOST_SUCCESS = "POST_EDITPOST_SUCCESS";
export const EDITPOST_FAILURE = "POST_EDITPOST_FAILURE";

export const DELETEPOST_REQUEST = "POST_DELETEPOST_REQUEST";
export const DELETEPOST_SUCCESS = "POST_DELETEPOST_SUCCESS";
export const DELETEPOST_FAILURE = "POST_DELETEPOST_FAILURE";

export const LIKEPOST_REQUEST = "POST_LIKEPOST_REQUEST";
export const LIKEPOST_SUCCESS = "POST_LIKEPOST_SUCCESS";
export const LIKEPOST_FAILURE = "POST_LIKEPOST_FAILURE";

export const DISLIKEPOST_REQUEST = "POST_DISLIKEPOST_REQUEST";
export const DISLIKEPOST_SUCCESS = "POST_DISLIKEPOST_SUCCESS";
export const DISLIKEPOST_FAILURE = "POST_DISLIKEPOST_FAILURE";

//

//userActions
export const REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const REGISTER_FAILURE = "USER_REGISTER_FAILURE";

export const LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const FIND_REQUEST = "USER_FIND_REQUEST";
export const FIND_SUCCESS = "USER_FIND_SUCCESS";
export const FIND_FAILURE = "USER_FIND_FAILURE";
 
export const DELETE_REQUEST = "USER_DELETE_REQUEST";
export const DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const DELETE_FAILURE = "USER_DELETE_FAILURE";
//
export const LOGOUT = "USER_LOGOUT";

//commentAction

export const ADDCOMMENT_REQUEST = "COMMENT_ADDCOMMENT_REQUEST";
export const ADDCOMMENT_SUCCESS = "COMMENT_ADDCOMMENT_SUCCESS";
export const ADDCOMMENT_FAILURE = "COMMENT_ADDCOMMENT_FAILURE";

export const DELETECOMMENT_REQUEST = "COMMENT_DELETECOMMENT_REQUEST";
export const DELETECOMMENT_SUCCESS = "COMMENT_DELETECOMMENT_SUCCESS";
export const DELETECOMMENT_FAILURE = "COMMENT_DELETECOMMENT_FAILURE";
