export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";

export const GET_POST_BY_ID_SUCCESS = "GET_POST_BY_ID";

export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";

export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
