//postActions
export const GETALL_REQUEST = "POST_GETALL_REQUEST";
export const GETALL_SUCCESS = "POST_GETALL_SUCCESS";
export const GETALL_FAILURE = "POST_GETALL_FAILURE";

export const SHAREPOST_REQUEST = "POST_SHAREPOST_REQUEST";
export const SHAREPOST_SUCCESS = "POST_SHAREPOST_SUCCESS";
export const SHAREPOST_FAILURE = "POST_SHAREPOST_FAILURE";

export const LIKEPOST_REQUEST = "POST_LIKEPOST_REQUEST";
export const LIKEPOST_SUCCESS = "POST_LIKEPOST_SUCCESS";
export const LIKEPOST_FAILURE = "POST_LIKEPOST_FAILURE";

//

//userActions
export const REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const REGISTER_FAILURE = "USER_REGISTER_FAILURE";

export const LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const DELETE_REQUEST = "USER_DELETE_REQUEST";
export const DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const DELETE_FAILURE = "USER_DELETE_FAILURE";
//
export const LOGOUT = "USER_LOGOUT";
